// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using etkinlik.Context;

#nullable disable

namespace etkinlik.Migrations
{
    [DbContext(typeof(TutorialDbContext))]
    [Migration("20240711063932_dbaktarma")]
    partial class dbaktarma
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("etkinlik.Models.AnaSayfa", b =>
                {
                    b.Property<int>("etkinlik_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("etkinlik_id"), 1L, 1);

                    b.Property<int>("detay_id")
                        .HasColumnType("int");

                    b.Property<int>("detay_id1")
                        .HasColumnType("int");

                    b.Property<string>("etkinlik_adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("etkinlik_resmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("etkinlik_tarih")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("etkinlik_id");

                    b.HasIndex("detay_id1");

                    b.ToTable("anaSayfas");
                });

            modelBuilder.Entity("etkinlik.Models.Detay", b =>
                {
                    b.Property<int>("detay_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("detay_id"), 1L, 1);

                    b.Property<string>("aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("fiyat")
                        .HasColumnType("real");

                    b.Property<string>("kategori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("saat")
                        .HasColumnType("real");

                    b.Property<DateTime>("tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("detay_id");

                    b.ToTable("detays");
                });

            modelBuilder.Entity("etkinlik.Models.EtkinlikOlustur", b =>
                {
                    b.Property<int>("olusturma_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("olusturma_id"), 1L, 1);

                    b.Property<string>("aciklamasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("tarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("olusturma_id");

                    b.ToTable("etkinlikOlusturs");
                });

            modelBuilder.Entity("etkinlik.Models.Login", b =>
                {
                    b.Property<int>("Login_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Login_id"), 1L, 1);

                    b.Property<string>("Kullanici_adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("signupSign_id")
                        .HasColumnType("int");

                    b.HasKey("Login_id");

                    b.HasIndex("signupSign_id");

                    b.ToTable("logins");
                });

            modelBuilder.Entity("etkinlik.Models.Signup", b =>
                {
                    b.Property<int>("Sign_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sign_id"), 1L, 1);

                    b.Property<string>("Kullanici_adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sign_id");

                    b.ToTable("signups");
                });

            modelBuilder.Entity("etkinlik.Models.AnaSayfa", b =>
                {
                    b.HasOne("etkinlik.Models.Detay", "detay")
                        .WithMany()
                        .HasForeignKey("detay_id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("detay");
                });

            modelBuilder.Entity("etkinlik.Models.Login", b =>
                {
                    b.HasOne("etkinlik.Models.Signup", "signup")
                        .WithMany()
                        .HasForeignKey("signupSign_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("signup");
                });
#pragma warning restore 612, 618
        }
    }
}
