// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using etkinlik.Context;

#nullable disable

namespace etkinlik.Migrations
{
    [DbContext(typeof(TutorialDbContext))]
    [Migration("20240711133823_anasayfaguncel")]
    partial class anasayfaguncel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("etkinlik.Models.AnaSayfa", b =>
                {
                    b.Property<int>("etkinlik_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("etkinlik_id"), 1L, 1);

                    b.Property<int>("detay_id")
                        .HasColumnType("int");

                    b.Property<string>("etkinlik_adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("etkinlik_resmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("etkinlik_tarih")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("etkinlik_id");

                    b.ToTable("anaSayfas");
                });

            modelBuilder.Entity("etkinlik.Models.Detay", b =>
                {
                    b.Property<int>("detay_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("detay_id"), 1L, 1);

                    b.Property<string>("aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("fiyat")
                        .HasColumnType("real");

                    b.Property<string>("kategori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("saat")
                        .HasColumnType("real");

                    b.Property<DateTime>("tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("detay_id");

                    b.ToTable("detays");
                });

            modelBuilder.Entity("etkinlik.Models.EtkinlikOlustur", b =>
                {
                    b.Property<int>("olusturma_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("olusturma_id"), 1L, 1);

                    b.Property<string>("aciklamasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("tarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("olusturma_id");

                    b.ToTable("etkinlikOlusturs");
                });

            modelBuilder.Entity("etkinlik.Models.Login", b =>
                {
                    b.Property<int>("login_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("login_id"), 1L, 1);

                    b.Property<string>("kullanici_adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sign_id")
                        .HasColumnType("int");

                    b.HasKey("login_id");

                    b.ToTable("logins");
                });

            modelBuilder.Entity("etkinlik.Models.Signup", b =>
                {
                    b.Property<int>("sign_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sign_id"), 1L, 1);

                    b.Property<string>("kullanici_adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sign_id");

                    b.ToTable("signups");
                });
#pragma warning restore 612, 618
        }
    }
}
